### ISSUE TITLE
Units spawn in water around costal named areas.

### ISSUE THREAD

**Issue by Andrews135** [LISTINGS09/A3_Mission_Generator#2]
First message on this site. Am interested in this script. Is this active support or no longer?

1. Issue I have seen is the cities located on islands off main map like north stratis spawn units as close to that named area as possible. But unfortunately dump the units in to the water.  Is this something you can fix or ignore? Thanks.

**Comment by LISTINGS09** [comment]
Answer: Its doing the best it can.

[fnc_ai_ups.sqf line: 198] When spawning units it will check 25 times to try and find land randomly in the location. The more water you have around the location, the more chance you have of them spawning in water.  You could try changing this to higher but it will never be 100%.

Arma can tell if a unit is on land or sea, but if you're in the sea, there isn't a quick way to know where the nearest land is. There are ways, but when you're spawning many units, it really slows things down.

Their waypoints should never take them out to sea though, so over time any unit at sea should all find their way to dry land.

**Comment by Andrews135** [comment]
Ok. Thanks for the response.  I will increase the check times. The real issue is the smaller islands like north stratis having a city name. Is this project still being worked on like the other missions commented out?

**Comment by LISTINGS09** [comment]
Still being worked on, it shouldn't be marking any locations if N,S,E and West are all water, but I just noticed what you describe on Stratis myself, will have a look into whats going on.

**Comment by Andrews135** [comment]
Hey. Could you tell me about the different modes?  And can I pick a spot for the commander or does it spawn near the units placed in editor?  A setup guide would be really nice. How does it choose the enemy rhs units?

**Comment by Andrews135** [comment]
Also, which file is the zone checker in to increase its checks for water?

**Comment by LISTINGS09** [comment]
ZZM_Mode 0 - Designed for 1 mission in 1 area - Leaders can select a location/single area.
ZZM_Mode 1 - Designed for open-ended gameplay. Each location on the map has an intel case, that will reveal a mission, either find the cases and do the missions or clear each location of enemy forces then move to the next one.
ZZM_Mode 2 - Designed for open-ended gameplay. Commander spawns at base (respawn marker) to issue missions to players (similar to partrol ops, if you've played that)

All the units are handled by configs in the main folder. Its designed to be easily ported between maps so the commander is generally the 'leader'.

'zmm_setup_world.sqf' determines the locations, I've fixed the water check this version but Line 48 controls the ratio of land needed to determine a valid location.

**Comment by Andrews135** [comment]
Thanks for the update. You may not realize but the DL is not in the ZMM folder so one has make that folder, drop the files in and there is no scripts folder so I had to edit some of the call lines. Just FYI. This sounds like a nice mission generator.   Thanks for making it. I will update the fixed file soon.
So for rhs. If I am us and want both opfor and indy units to fight is that possible?

**Comment by LISTINGS09** [comment]
There is a 'ZMM_FolderLocation' which can be changed to reference where anyone might want to put the scripts into, then running the 'zmm_init.sqf' will kick everything off.

The map will randomly populate the area with whichever sides the player isn't. The parameters (f_param_factionWest, f_param_factionEast, f_param_factionGuer) will select the types of units in the chosen template file (zmm_factions_xxx.sqf), the unit template loaded is set with the 'ZZM_Template' variable.

For our missions I set these in mission parameters (https://community.bistudio.com/wiki/Mission_Parameters) otherwise you can hard-code it with 'ZZM_Template = "RHS"; f_param_factionEast = 5; f_param_factionGuer = 2;' etc.

I don't use RHS anymore so some of the classnames given in the template may be incorrect if there's been many updates from RHS.
